language: node_js
node_js:
  - '10'
  - '12'

script:
  - make lint
  - make cover
  - make build
  - make docs

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages (only on Linux)
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master

  # Do a semantic release
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
