language: node_js
node_js:
  - '10'
  - '12'

os: linux

script:
  - make lint
  - make cover
  - make build
  - make docs

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages (only on Linux)
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    cleanup: false
    token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_NODE_VERSION = '12'

  # Do a semantic release
  - provider: script
    cleanup: false
    script: npx semantic-release
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_NODE_VERSION = '12'
